openapi: 3.1.0
info:
  title: Order API
  version: 1.0.0
  description: REST API for retrieving Orders including passenger information and line items.

servers:
  - url: https://api.airline.com/v1

paths:
  /orders:
    get:
      summary: List all orders
      operationId: listOrders
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /orders/search:
    get:
      summary: Search orders by flight number
      operationId: searchOrders
      parameters:
        - name: flightNumber
          in: query
          required: true
          schema:
            x-business-definition: "file://business-definitions/flight/flight_number.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
          x-business-definition: "file://business-definitions/order/order_id.yaml"
        orderStatus:
          x-business-definition: "file://business-definitions/order/order_status.yaml"
        totalAmount:
          x-business-definition: "file://business-definitions/order/total_amount.yaml"
        passengerName:
          x-business-definition: "file://business-definitions/passenger/passenger_name.yaml"
        passengerDateOfBirth:
          type: string
          format: date
          x-business-definition: "file://business-definitions/passenger/passenger_date_of_birth.yaml"
        lineItems:
          type: array
          items:
            type: object
            properties:
              lineItemNo:
                x-business-definition: "file://business-definitions/order/line_item_no.yaml"
              flightNumber:
                x-business-definition: "file://business-definitions/flight/flight_number.yaml"
              quantity:
                x-business-definition: "file://business-definitions/order/quantity.yaml"
              unitPrice:
                x-business-definition: "file://business-definitions/order/unit_price.yaml"
