apiVersion: v3.1.0
kind: DataContract
id: 550e8400-e29b-41d4-a716-446655440001
name: Orders Data Contract (apidays 2025 - demo)
version: 1.0.0
status: active
domain: order-management
description:
  purpose: Data contract for Order data including order details, passenger information,
    and line items.
tags:
- order
schema:
- name: order
  description: Contains order header information including customer, totals, and passenger
    details.
  physicalType: table
  physicalName: T_ORD_HDR_01
  quality:
  - type: sql
    name: order-total-sum-check
    description: Total amount must equal sum of line item totals (quantity * unit_price)
    query: 'SELECT o.order_id

      FROM orders o

      LEFT JOIN order_line_items oli ON o.order_id = oli.order_id

      GROUP BY o.order_id, o.total_amount

      HAVING o.total_amount != COALESCE(SUM(oli.quantity * oli.unit_price), 0)

      '
    mustBe: 0
  properties:
  - name: order_id
    physicalName: ORD_ID
    physicalType: uuid
    required: true
    unique: true
    primaryKey: true
    primaryKeyPosition: 1
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/order_id.yaml
    businessName: Order ID
    logicalType: string
    description: A unique identifier for the Order.
    classification: internal
    examples:
    - 550e8400-e29b-41d4-a716-446655440000
    logicalTypeOptions:
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    customProperties:
    - property: pii
      value: false
  - name: order_status
    physicalName: ORD_STS_CD
    physicalType: varchar(20)
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/order_status.yaml
    businessName: Order Status
    logicalType: string
    description: The current status of the Order lifecycle.
    classification: internal
    examples:
    - CONFIRMED
    customProperties:
    - property: pii
      value: false
  - name: total_amount
    physicalName: TOT_AMT
    physicalType: decimal(10,2)
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/total_amount.yaml
    businessName: Total Amount
    logicalType: number
    description: The total monetary amount of the Order including all fees and taxes.
    classification: confidential
    examples:
    - '1299.99'
    customProperties:
    - property: pii
      value: false
  - name: passenger_name
    physicalName: PAX_NM
    physicalType: varchar(200)
    required: true
    criticalDataElement: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/passenger/passenger_name.yaml
    businessName: Passenger Name
    logicalType: string
    description: The full name of the passenger.
    classification: sensitive
    examples:
    - John Smith
    customProperties:
    - property: pii
      value: true
  - name: passenger_date_of_birth
    physicalName: PAX_DOB
    physicalType: date
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/passenger/passenger_date_of_birth.yaml
    businessName: Passenger Date of Birth
    logicalType: date
    description: The date of birth of the passenger
    classification: sensitive
    examples:
    - '1985-03-15'
    criticalDataElement: true
    customProperties:
    - property: pii
      value: true
  - name: inserted_at
    physicalName: INS_TS
    physicalType: timestamp
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/technical/inserted_at.yaml
    businessName: Inserted At
    logicalType: timestamp
    description: Timestamp when the record was inserted into the database.
    classification: internal
    examples:
    - '2025-12-03T10:30:00Z'
    customProperties:
    - property: pii
      value: false
- name: order_line_items
  description: Contains individual line items for each order, including flight and
    pricing information.
  physicalType: table
  physicalName: T_ORD_LI_DTL_01
  properties:
  - name: order_id
    physicalName: ORD_ID
    physicalType: uuid
    required: true
    primaryKey: true
    primaryKeyPosition: 1
    relationships:
    - type: foreignKey
      to: order.order_id
    customProperties:
    - property: references
      value: order.order_id
    - property: pii
      value: false
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/order_id.yaml
    businessName: Order ID
    logicalType: string
    description: A unique identifier for the Order.
    classification: internal
    examples:
    - 550e8400-e29b-41d4-a716-446655440000
    logicalTypeOptions:
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
  - name: line_item_no
    physicalName: LN_ITM_NBR
    physicalType: int
    required: true
    primaryKey: true
    primaryKeyPosition: 2
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/line_item_no.yaml
    businessName: Line Item Number
    logicalType: integer
    description: The sequential number of a line item within an order.
    classification: internal
    examples:
    - 1
    customProperties:
    - property: pii
      value: false
  - name: flight_number
    physicalName: FLT_NBR
    physicalType: varchar(10)
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/flight/flight_number.yaml
    businessName: Flight Number
    logicalType: string
    description: The airline flight number consisting of a two-letter airline code
      followed by up to four digits.
    classification: internal
    examples:
    - LH123
    logicalTypeOptions:
      pattern: ^[A-Z]{2}\d{1,4}$
    customProperties:
    - property: pii
      value: false
  - name: quantity
    physicalName: QTY
    physicalType: int
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/quantity.yaml
    businessName: Quantity
    logicalType: integer
    description: The number of units for an Order Item.
    classification: internal
    examples:
    - 1
    customProperties:
    - property: pii
      value: false
  - name: unit_price
    physicalName: UNT_PRC
    physicalType: decimal(10,2)
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/order/unit_price.yaml
    businessName: Unit Price
    logicalType: number
    description: The price per unit for an Order Item.
    classification: confidential
    examples:
    - 149.99
    customProperties:
    - property: pii
      value: false
  - name: inserted_at
    physicalName: INS_TS
    physicalType: timestamp
    required: true
    authoritativeDefinitions:
    - type: definition
      url: file://business-definitions/technical/inserted_at.yaml
    businessName: Inserted At
    logicalType: timestamp
    description: Timestamp when the record was inserted into the database.
    classification: internal
    examples:
    - '2025-12-03T10:30:00Z'
    customProperties:
    - property: pii
      value: false
servers:
- server: databricks-prod
  type: databricks
  environment: production
  catalog: airline_catalog
  schema: order_management
slaProperties:
- property: retention
  value: 1
  unit: year
support:
- channel: email
  url: mailto:order-management-team@airline.com
- channel: teams
  url: https://teams.microsoft.com/l/channel/order-management-support
